### PR TITLE
Add fallback facet name

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by vvo** [comment]
Sorry for late reply

**Comment by vvo** [comment]
Thanks a lot!

**Comment by vvo** [comment]
Did you see our https://community.algolia.com/instantsearch.js/ project? I wonder as a dev experience on Algolia.com, which projects did you discover/seen at first.

**Comment by Kikobeats** [comment]
ops, sorry, I added context at first comment :)

**Pull request merged**
