### PR TITLE
Prevent the outdated hits to get rendered and also improve the highlighted results.

### PR DESCRIPTION
**Pull request by attomos**
Found this from Algolia JavaScript documentation.
https://www.algolia.com/doc/javascript#UIInstantSearch

### CODE REVIEW

**Comment by redox** [comment]
Thanks for the bug fix @attomos. The good thing is that it's now part of the underlying helper, can you confirm @bobylito? Is it already used by the instant search demo?

**Comment by bobylito** [comment]
It's part of the currently unreleased helper. Release will be very soon :) And then I'll update the project.

**Comment by bobylito** [comment]
The new helper version has been released will update asap :)

**Comment by vvo** [comment]
I do think this is now fixed @attomos, we released a new helper can you check if the demo works for you now?

**Comment by attomos** [comment]
It works, @vvo : )

**Pull request closed without merging**
